name: Release packages

on:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: "--max_old_space_size=4096"

permissions:
  pull-requests: write
  contents: write
  packages: write

jobs:
  release:
    if: github.repository == 'imjustlucas/imjustlucas'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: "latest"

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to Github Packages
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
          commit: "🔖 release version"
          title: "🔖 release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}